// Writes what came in with the last pull into the till's "What's new" page.
//   node tools/update-log.mjs            the last 80 commits
//   node tools/update-log.mjs --since 14 only the last 14 days
//   node tools/update-log.mjs --n 200    a longer list
//
// Run it after a pull. It reads the git history and replaces the block between the two
// markers in app/index.html — nothing else in the file is touched. The page is meant to
// be temporary: take the menu entry and this script out when it has served its purpose.
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const APP = path.resolve(here, '../app/index.html');
const arg = (k, d) => { const i = process.argv.indexOf('--' + k); return i >= 0 ? process.argv[i + 1] : d };
const n = Math.max(1, Math.min(500, +arg('n', 80) || 80));
const since = arg('since', null);

const git = (...a) => execFileSync('git', a, { cwd: path.resolve(here, '..'), encoding: 'utf8' }).trim();

const SEP = '\u001f', ROW = '\u001e';
const fmt = ['%h', '%ad', '%an', '%s'].join(SEP);
const args = ['log', `--pretty=format:${fmt}${ROW}`, '--date=format:%Y-%m-%d %H:%M', `-n${n}`];
if (since) args.push(`--since=${since} days ago`);

const items = git(...args).split(ROW).map(r => r.trim()).filter(Boolean).map(r => {
  const [h, d, who, ...rest] = r.split(SEP);
  return { h, d, who, s: rest.join(SEP) };
});

const head = git('rev-parse', '--short', 'HEAD');
const at = new Date().toLocaleString('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit', hour12: false });
const esc = s => String(s).replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\r?\n/g, ' ');

const block = `const UPDATE_LOG={at:'${esc(at)}',head:'${esc(head)}',count:${items.length},items:[
${items.map(i => ` {h:'${esc(i.h)}',d:'${esc(i.d)}',w:'${esc(i.who)}',s:'${esc(i.s)}'}`).join(',\n')}
]};`;

const START = '/* <<UPDATE-LOG>> generated by tools/update-log.mjs — do not edit by hand */';
const END = '/* <</UPDATE-LOG>> */';

// Only what lies between the markers is rewritten. The file has a mix of line endings and
// normalising it would put 550 untouched lines into the diff, so the block takes the ending
// of the line the marker sits on and everything else is left exactly as it was.
const src = fs.readFileSync(APP, 'utf8');
const a = src.indexOf(START), b = src.indexOf(END);
if (a < 0 || b < 0 || b < a) {
  console.error('The markers are not in app/index.html — put them back, or the page has been taken out.');
  process.exit(1);
}
const nl = src.indexOf('\n', a);
const eol = (nl > 0 && src[nl - 1] === '\r') ? '\r\n' : '\n';
fs.writeFileSync(APP, src.slice(0, a) + (START + '\n' + block + '\n').replace(/\n/g, eol) + src.slice(b));

console.log(`What's new: ${items.length} change${items.length === 1 ? '' : 's'} up to ${head}, marked as brought in on ${at}`);
